import type { ParamDef } from './shader-def-types.js';

export const commonParams: Record<string, ParamDef> = {
  speed: {
    name: 'speed',
    type: 'number',
    defaultValue: 1,
    description: 'Animation speed',
  },
  frame: {
    name: 'frame',
    type: 'number',
    defaultValue: 0,
    description: 'Starting animation frame',
  },
  scale: {
    name: 'scale',
    type: 'number',
    min: 0.01,
    max: 4,
    defaultValue: 1,
    description: 'Overall zoom level of the graphics',
  },
  rotation: {
    name: 'rotation',
    type: 'number',
    min: 0,
    max: 360,
    defaultValue: 0,
    description: 'Overall rotation angle of the graphics',
  },
  offsetX: {
    name: 'offsetX',
    type: 'number',
    min: -1,
    max: 1,
    defaultValue: 0,
    description: 'Horizontal offset of the graphics center',
  },
  offsetY: {
    name: 'offsetY',
    type: 'number',
    min: -1,
    max: 1,
    defaultValue: 0,
    description: 'Vertical offset of the graphics center',
  },
  width: {
    name: 'width',
    type: 'number | string',
    description: 'CSS width style of the shader element',
  },
  height: {
    name: 'height',
    type: 'number | string',
    description: 'CSS height style of the shader element',
  },
  fit: {
    name: 'fit',
    type: 'enum',
    description: 'How to fit the rendered shader into the canvas dimensions',
    options: ['contain', 'cover'],
  },
  worldWidth: {
    name: 'worldWidth',
    type: 'number',
    description: "Virtual width of the graphic before it's scaled to fit the canvas",
  },
  worldHeight: {
    name: 'worldHeight',
    type: 'number',
    description: "Virtual height of the graphic before it's scaled to fit the canvas",
  },
  originX: {
    name: 'originX',
    type: 'number',
    min: 0,
    max: 1,
    description: 'Reference point for positioning world width in the canvas',
  },
  originY: {
    name: 'originY',
    type: 'number',
    min: 0,
    max: 1,
    description: 'Reference point for positioning world height in the canvas',
  },
  minPixelRatio: {
    name: 'minPixelRatio',
    type: 'number',
    description: 'Minimum pixel ratio to use when rendering the shader',
  },
  maxPixelCount: {
    name: 'maxPixelCount',
    type: 'number',
    description: 'Maximum pixel count that the shader may process',
  },
} as const;

export const animatedCommonParams: ParamDef[] = [
  commonParams.speed!,
  commonParams.frame!,
  commonParams.scale!,
  commonParams.rotation!,
  commonParams.offsetX!,
  commonParams.offsetY!,
  commonParams.width!,
  commonParams.height!,
  commonParams.fit!,
  commonParams.worldWidth!,
  commonParams.worldHeight!,
  commonParams.originX!,
  commonParams.originY!,
  commonParams.minPixelRatio!,
  commonParams.maxPixelCount!,
];

export const staticCommonParams: ParamDef[] = [
  commonParams.scale!,
  commonParams.rotation!,
  commonParams.offsetX!,
  commonParams.offsetY!,
  commonParams.width!,
  commonParams.height!,
  commonParams.fit!,
  commonParams.worldWidth!,
  commonParams.worldHeight!,
  commonParams.originX!,
  commonParams.originY!,
  commonParams.minPixelRatio!,
  commonParams.maxPixelCount!,
];
