import { flutedGlassPresets } from '@paper-design/shaders-react';
import type { ShaderDef } from './shader-def-types';
import { staticCommonParams } from './common-param-def';

const defaultParams = flutedGlassPresets[0].params;

export const flutedGlassDef: ShaderDef = {
  name: 'Fluted Glass',
  description:
    'Fluted glass image filter transforms an image into streaked, ribbed distortions, giving a mix of clarity and obscurity.',
  params: [
    {
      name: 'image',
      type: 'HTMLImageElement | string',
      description: 'The image to use for the effect',
    },
    {
      name: 'colorBack',
      type: 'string',
      defaultValue: defaultParams.colorBack,
      isColor: true,
      description: 'Background color',
    },
    {
      name: 'colorShadow',
      type: 'string',
      defaultValue: defaultParams.colorShadow,
      isColor: true,
      description: 'Shadow color',
    },
    {
      name: 'shadows',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.shadows,
      description: 'A power of color layer added over the image and background, following the distortion shape',
    },
    {
      name: 'strokes',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.strokes,
      description: 'Thin stokes along distortion shape filled with background color; useful for antialiasing on the small grid',
    },
    {
      name: 'size',
      type: 'number',
      min: 0,
      max: 1,
      step: 0.001,
      defaultValue: defaultParams.size,
      description: 'The size of the distortion shape grid',
    },
    {
      name: 'shape',
      type: 'enum',
      defaultValue: defaultParams.shape,
      description: 'The shape of the grid',
      options: ['pattern', 'wave', 'lines', 'linesIrregular', 'zigzag'],
    },
    {
      name: 'angle',
      type: 'number',
      min: 0,
      max: 180,
      defaultValue: defaultParams.angle,
      description: 'Direction of the grid relative to the image',
    },
    {
      name: 'distortionShape',
      type: 'enum',
      defaultValue: defaultParams.distortionShape,
      description: 'The shape of the distortion',
      options: ['prism', 'lens', 'contour', 'cascade', 'facete'],
    },
    {
      name: 'distortion',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.distortion,
      description: 'The power of distortion applied within each stripe',
    },
    {
      name: 'shift',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.shift,
      description: 'Texture shift in direction opposite to the grid',
    },
    {
      name: 'edges',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.edges,
      description: 'Extra distortion along the grid lines',
    },
    {
      name: 'blur',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.blur,
      description: 'One-directional blur over the image and extra blur around the edges',
    },
    {
      name: 'margin',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: undefined,
      description: 'Distance from image edges to the effect',
    },
    {
      name: 'marginLeft',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.marginLeft,
      description: 'Distance from the left edge to the effect',
    },
    {
      name: 'marginRight',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.marginRight,
      description: 'Distance from the right edge to the effect',
    },
    {
      name: 'marginTop',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.marginTop,
      description: 'Distance from the top edge to the effect',
    },
    {
      name: 'marginBottom',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.marginBottom,
      description: 'Distance from the bottom edge to the effect',
    },
    ...staticCommonParams,
  ],
};
