import { halftoneCmykPresets } from '@paper-design/shaders-react';
import type { ShaderDef } from './shader-def-types';
import { staticImageCommonParams } from './common-param-def';

const defaultParams = halftoneCmykPresets[0].params;

export const halftoneCmykDef: ShaderDef = {
  name: 'Halftone CMYK',
  description: 'CMYK halftone printing effect with customizable dot patterns and ink colors for each channel',
  params: [
    {
      name: 'image',
      type: 'HTMLImageElement | string',
      description: 'The image to use for the effect',
    },
    {
      name: 'colorBack',
      type: 'string',
      defaultValue: defaultParams.colorBack,
      isColor: true,
      description: 'Background (paper) color',
    },
    {
      name: 'colorC',
      type: 'string',
      defaultValue: defaultParams.colorC,
      isColor: true,
      description: 'Cyan ink color (alpha controls layer transparency, not dot size)',
    },
    {
      name: 'colorM',
      type: 'string',
      defaultValue: defaultParams.colorM,
      isColor: true,
      description: 'Magenta ink color (alpha controls layer transparency, not dot size)',
    },
    {
      name: 'colorY',
      type: 'string',
      defaultValue: defaultParams.colorY,
      isColor: true,
      description: 'Yellow ink color (alpha controls layer transparency, not dot size)',
    },
    {
      name: 'colorK',
      type: 'string',
      defaultValue: defaultParams.colorK,
      isColor: true,
      description: 'Black ink color (alpha controls layer transparency, not dot size)',
    },
    {
      name: 'size',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.size,
      description: 'Halftone cell size (0 = fine, 1 = coarse)',
    },
    {
      name: 'contrast',
      type: 'number',
      min: 0,
      max: 2,
      defaultValue: defaultParams.contrast,
      description: 'Image contrast adjustment',
    },
    {
      name: 'rounded',
      type: 'boolean',
      defaultValue: defaultParams.rounded,
      description: 'Use per-cell color sampling (true) or blurred sampling (false)',
      options: ['true', 'false'],
    },
    {
      name: 'softness',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.softness,
      description: 'Edge softness of dots/lines',
    },
    {
      name: 'grainSize',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainSize,
      description: 'Size of grain overlay texture',
    },
    {
      name: 'grainMixer',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainMixer,
      description: 'Strength of grain affecting dot size',
    },
    {
      name: 'grainOverlay',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainOverlay,
      description: 'Strength of grain overlay on final output',
    },
    {
      name: 'gridNoise',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.gridNoise,
      description: 'Displaces both dot positions and color sampling points; naturally makes more paper visible',
    },
    {
      name: 'addonC',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.addonC,
      description: 'Flat cyan dot size adjustment applied uniformly to all dots',
    },
    {
      name: 'addonM',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.addonM,
      description: 'Flat magenta dot size adjustment applied uniformly to all dots',
    },
    {
      name: 'addonY',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.addonY,
      description: 'Flat yellow dot size adjustment applied uniformly to all dots',
    },
    {
      name: 'addonK',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.addonK,
      description: 'Flat black dot size adjustment applied uniformly to all dots',
    },
    {
      name: 'boostC',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.boostC,
      description: 'Proportional cyan boost that enhances existing dots',
    },
    {
      name: 'boostM',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.boostM,
      description: 'Proportional magenta boost that enhances existing dots',
    },
    {
      name: 'boostY',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.boostY,
      description: 'Proportional yellow boost that enhances existing dots',
    },
    {
      name: 'boostK',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.boostK,
      description: 'Proportional black boost that enhances existing dots',
    },
    {
      name: 'shape',
      type: 'enum',
      defaultValue: defaultParams.shape,
      description: 'Dot shape style',
      options: ['separate', 'joined'],
    },
    ...staticImageCommonParams,
  ],
};
