import { halftoneLinesPresets } from '@paper-design/shaders-react';
import type { ShaderDef } from './shader-def-types';
import { staticImageCommonParams } from './common-param-def';

const defaultParams = halftoneLinesPresets[0].params;

export const halftoneLinesDef: ShaderDef = {
  name: 'Halftone lines',
  description:
    'Image filter pattern made of a line grid with optional stroke thickness and grid distortion; offering multiple grid types, grid distortions, and color palettes',
  params: [
    {
      name: 'image',
      type: 'HTMLImageElement | string',
      description: 'The image to use for the effect',
    },
    {
      name: 'colorBack',
      type: 'string',
      defaultValue: defaultParams.colorBack,
      isColor: true,
      description: 'Background color',
    },
    {
      name: 'colorFront',
      type: 'string',
      defaultValue: defaultParams.colorFront,
      isColor: true,
      description: 'Foreground color',
    },
    {
      name: 'originalColors',
      type: 'boolean',
      defaultValue: defaultParams.originalColors,
      description: 'Use the sampled image’s original colors instead of colorFront',
      options: ['true', 'false'],
    },
    {
      name: 'contrast',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.contrast,
      description: 'Contrast applied to the sampled image',
    },
    {
      name: 'inverted',
      type: 'boolean',
      defaultValue: defaultParams.inverted,
      description: 'Inverts the image luminance',
      options: ['true', 'false'],
    },
    {
      name: 'smoothness',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.smoothness,
      description: 'The size of blur applied to original image, the more image is blurred the smoother is stroke shape',
    },
    {
      name: 'stripeWidth',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.stripeWidth,
      description: 'The max width of halftone stroke shape, relative to grid size',
    },
    {
      name: 'thinLines',
      type: 'boolean',
      defaultValue: defaultParams.thinLines,
      description: 'Allows thin 1px strokes (set to false for proper antialiasing)',
      options: ['true', 'false'],
    },
    {
      name: 'allowOverflow',
      type: 'boolean',
      defaultValue: defaultParams.allowOverflow,
      description:
        'Allows thin stripeWidth to take the whole grid size (set to false to make grid lines always visible)',
      options: ['true', 'false'],
    },
    {
      name: 'grid',
      type: 'enum',
      defaultValue: defaultParams.grid,
      description: 'Grid type',
      options: ['lines', 'radial', 'waves', 'noise'],
    },
    {
      name: 'size',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.size,
      description: 'Grid size relative to the image box',
    },
    {
      name: 'gridOffsetX',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.gridOffsetX,
      description: 'The horizontal offset of grid relative to the image box',
    },
    {
      name: 'gridOffsetY',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.gridOffsetY,
      description: 'The vertical offset of grid relative to the image box',
    },
    {
      name: 'gridRotation',
      type: 'number',
      min: 0,
      max: 360,
      defaultValue: defaultParams.gridRotation,
      description: 'The grid rotation around image center (not efficient for radial grid + zero grid offsets)',
    },
    {
      name: 'gridAngleDistortion',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.gridAngleDistortion,
      description: 'Changing the grid rotation on the darker image areas',
    },
    {
      name: 'gridNoiseDistortion',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.gridNoiseDistortion,
      description: 'Applying noise to the grid on the darker image areas',
    },
    {
      name: 'grainMixer',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainMixer,
      description: 'Strength of grain distortion applied to strokes',
    },
    {
      name: 'grainMixerSize',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainMixerSize,
      description: 'The scale applied to the grain distortion',
    },
    {
      name: 'grainOverlay',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainOverlay,
      description: 'Post-processing b/w grainy overlay',
    },
    {
      name: 'grainOverlaySize',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainOverlaySize,
      description: 'The scale applied to the grain overlay',
    },
    ...staticImageCommonParams,
  ],
};
