import { halftoneCmykPresets } from '@paper-design/shaders-react';
import type { ShaderDef } from './shader-def-types';
import { staticImageCommonParams } from './common-param-def';

const defaultParams = halftoneCmykPresets[0].params;

export const halftoneCmykDef: ShaderDef = {
  name: 'Halftone CMYK',
  description: 'CMYK halftone printing effect with customizable dot patterns and ink colors for each channel',
  params: [
    {
      name: 'image',
      type: 'HTMLImageElement | string',
      description: 'The image to use for the effect',
    },
    {
      name: 'colorBack',
      type: 'string',
      defaultValue: defaultParams.colorBack,
      isColor: true,
      description: 'Background (paper) color',
    },
    {
      name: 'colorC',
      type: 'string',
      defaultValue: defaultParams.colorC,
      isColor: true,
      description: 'Cyan ink color (alpha controls layer transparency, not dot size)',
    },
    {
      name: 'colorM',
      type: 'string',
      defaultValue: defaultParams.colorM,
      isColor: true,
      description: 'Magenta ink color (alpha controls layer transparency, not dot size)',
    },
    {
      name: 'colorY',
      type: 'string',
      defaultValue: defaultParams.colorY,
      isColor: true,
      description: 'Yellow ink color (alpha controls layer transparency, not dot size)',
    },
    {
      name: 'colorK',
      type: 'string',
      defaultValue: defaultParams.colorK,
      isColor: true,
      description: 'Black ink color (alpha controls layer transparency, not dot size)',
    },
    {
      name: 'size',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.size,
      description: 'Grid size (relative to image box)',
    },
    {
      name: 'gridNoise',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.gridNoise,
      description: 'Displaces both dot positions and color sampling points; naturally makes the background more visible',
    },
    {
      name: 'type',
      type: 'enum',
      defaultValue: defaultParams.type,
      description: 'Dot type style',
      options: ['dots', 'ink', 'sharp'],
    },
    {
      name: 'softness',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.softness,
      description: 'Dots edge softness',
    },
    {
      name: 'contrast',
      type: 'number',
      min: 0,
      max: 2,
      defaultValue: defaultParams.contrast,
      description: 'Input image contrast',
    },
    {
      name: 'floodC',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.floodC,
      description: 'Uniform cyan flood applied to all dots',
    },
    {
      name: 'floodM',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.floodM,
      description: 'Uniform magenta flood applied to all dots',
    },
    {
      name: 'floodY',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.floodY,
      description: 'Uniform yellow flood applied to all dots',
    },
    {
      name: 'floodK',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.floodK,
      description: 'Uniform black flood applied to all dots',
    },
    {
      name: 'gainC',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.gainC,
      description: 'Proportional cyan gain that enhances existing dots',
    },
    {
      name: 'gainM',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.gainM,
      description: 'Proportional magenta gain that enhances existing dots',
    },
    {
      name: 'gainY',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.gainY,
      description: 'Proportional yellow gain that enhances existing dots',
    },
    {
      name: 'gainK',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.gainK,
      description: 'Proportional black gain that enhances existing dots',
    },
    {
      name: 'grainSize',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainSize,
      description: 'Size of grain overlay texture (relative to image box)',
    },
    {
      name: 'grainMixer',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainMixer,
      description: 'Strength of grain disturbing dots shape',
    },
    {
      name: 'grainOverlay',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainOverlay,
      description: 'Post-processing b/w grain overlay',
    },
    ...staticImageCommonParams,
  ],
};
