import { halftoneCmykPresets } from '@paper-design/shaders-react';
import type { ShaderDef } from './shader-def-types';
import { staticImageCommonParams } from './common-param-def';

const defaultParams = halftoneCmykPresets[0].params;

export const halftoneCmykDef: ShaderDef = {
  name: 'Halftone CMYK',
  description: 'CMYK halftone printing effect with customizable dot/line patterns, angles, and ink colors for each channel',
  params: [
    {
      name: 'image',
      type: 'HTMLImageElement | string',
      description: 'The image to use for the effect',
    },
    {
      name: 'colorBack',
      type: 'string',
      defaultValue: defaultParams.colorBack,
      isColor: true,
      description: 'Background (paper) color',
    },
    {
      name: 'colorC',
      type: 'string',
      defaultValue: defaultParams.colorC,
      isColor: true,
      description: 'Cyan ink color (alpha controls layer transparency, not dot size)',
    },
    {
      name: 'colorM',
      type: 'string',
      defaultValue: defaultParams.colorM,
      isColor: true,
      description: 'Magenta ink color (alpha controls layer transparency, not dot size)',
    },
    {
      name: 'colorY',
      type: 'string',
      defaultValue: defaultParams.colorY,
      isColor: true,
      description: 'Yellow ink color (alpha controls layer transparency, not dot size)',
    },
    {
      name: 'colorK',
      type: 'string',
      defaultValue: defaultParams.colorK,
      isColor: true,
      description: 'Black ink color (alpha controls layer transparency, not dot size)',
    },
    {
      name: 'size',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.size,
      description: 'Halftone cell size (0 = fine, 1 = coarse)',
    },
    {
      name: 'shiftC',
      type: 'number',
      min: -2,
      max: 2,
      defaultValue: defaultParams.shiftC,
      description: 'Cyan channel position offset',
    },
    {
      name: 'shiftM',
      type: 'number',
      min: -2,
      max: 2,
      defaultValue: defaultParams.shiftM,
      description: 'Magenta channel position offset',
    },
    {
      name: 'shiftY',
      type: 'number',
      min: -2,
      max: 2,
      defaultValue: defaultParams.shiftY,
      description: 'Yellow channel position offset',
    },
    {
      name: 'shiftK',
      type: 'number',
      min: -2,
      max: 2,
      defaultValue: defaultParams.shiftK,
      description: 'Black channel position offset',
    },
    {
      name: 'contrast',
      type: 'number',
      min: 0,
      max: 2,
      defaultValue: defaultParams.contrast,
      description: 'Image contrast adjustment',
    },
    {
      name: 'rounded',
      type: 'boolean',
      defaultValue: defaultParams.rounded,
      description: 'Use per-cell color sampling (true) or blurred sampling (false)',
      options: ['true', 'false'],
    },
    {
      name: 'softness',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.softness,
      description: 'Edge softness of dots/lines',
    },
    {
      name: 'grainSize',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainSize,
      description: 'Size of grain overlay texture',
    },
    {
      name: 'grainMixer',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainMixer,
      description: 'Strength of grain affecting dot size',
    },
    {
      name: 'grainOverlay',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainOverlay,
      description: 'Strength of grain overlay on final output',
    },
    {
      name: 'gridSampleNoise',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.gridSampleNoise,
      description: 'Displaces both dot positions and color sampling together (maintains color accuracy)',
    },
    {
      name: 'compensationC',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.compensationC,
      description: 'Cyan dot size compensation (0 = no change, positive = larger, negative = smaller)',
    },
    {
      name: 'compensationM',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.compensationM,
      description: 'Magenta dot size compensation (0 = no change, positive = larger, negative = smaller)',
    },
    {
      name: 'compensationY',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.compensationY,
      description: 'Yellow dot size compensation (0 = no change, positive = larger, negative = smaller)',
    },
    {
      name: 'compensationK',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.compensationK,
      description: 'Black dot size compensation (0 = no change, positive = larger, negative = smaller)',
    },
    {
      name: 'shape',
      type: 'enum',
      defaultValue: defaultParams.shape,
      description: 'Dot shape style',
      options: ['separate', 'joined'],
    },
    ...staticImageCommonParams,
  ],
};
