import { paperTexturePresets } from '@paper-design/shaders-react';
import type { ShaderDef } from './shader-def-types';

const defaultParams = paperTexturePresets[0].params;

export const paperTextureDef: ShaderDef = {
  name: 'Paper Texture',
  description: 'Mimicking paper texture with a combination of noises.',
  params: [
    {
      name: 'colorFront',
      type: 'string',
      defaultValue: defaultParams.colorFront,
      isColor: true,
      description: 'Colors used for the effect.',
    },
    {
      name: 'colorBack',
      type: 'string',
      defaultValue: defaultParams.colorBack,
      isColor: true,
      description: 'Colors used for the effect.',
    },
    {
      name: 'contrast',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.contrast,
      description: 'Mixing front and back colors.',
    },
    {
      name: 'roughness',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.roughness,
      description: 'Pixel noise, related to canvas (not scalable).',
    },
    {
      name: 'fiber',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.fiber,
      description: 'Curly-shaped noise.',
    },
    {
      name: 'fiberScale',
      type: 'number',
      min: 0.1,
      max: 2,
      defaultValue: defaultParams.fiberScale,
      description: 'Curly-shaped noise scale.',
    },
    {
      name: 'crumples',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.crumples,
      description: 'Cell-based pattern.',
    },
    {
      name: 'crumplesScale',
      type: 'number',
      min: 0.3,
      max: 3,
      defaultValue: defaultParams.crumplesScale,
      description: 'Cell-based pattern scale.',
    },
    {
      name: 'folds',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.folds,
      description: 'Depth of the folds.',
    },
    {
      name: 'foldsNumber',
      type: 'number',
      min: 1,
      max: 15,
      step: 1,
      defaultValue: defaultParams.foldsNumber,
      description: 'Number of folds (15 max).',
    },
    {
      name: 'blur',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.blur,
      description: 'Big-scale noise mask applied to everything but roughness.',
    },
    {
      name: 'drops',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.drops,
      description: 'Metaballs-like pattern.',
    },
    {
      name: 'seed',
      type: 'number',
      min: 0,
      max: 10,
      defaultValue: defaultParams.seed,
      description: 'Applied to folds, crumples and dots.',
    },
    {
      name: 'scale',
      type: 'number',
      min: 0.5,
      max: 10,
      defaultValue: defaultParams.scale,
      description: 'Overall pattern zoom.',
    },
    {
      name: 'fit',
      type: 'string',
      defaultValue: defaultParams.fit,
      description: 'How the image fits the canvas.',
      options: ['contain', 'cover'],
    },
  ],
};
