import { paperTexturePresets } from '@paper-design/shaders-react';
import type { ShaderDef } from './shader-def-types';
import { staticImageCommonParams } from './common-param-def';

const defaultParams = paperTexturePresets[0].params;

export const paperTextureDef: ShaderDef = {
  name: 'Paper Texture',
  description:
    'A static texture built from multiple noise layers, usable for a realistic paper and cardboard surfaces. Can be used as a image filter or as a texture.',
  params: [
    {
      name: 'image',
      type: 'HTMLImageElement | string',
      description: 'The image to use for the effect',
    },
    {
      name: 'colorBack',
      type: 'string',
      defaultValue: defaultParams.colorBack,
      isColor: true,
      description: 'Background color',
    },
    {
      name: 'colorFront',
      type: 'string',
      defaultValue: defaultParams.colorFront,
      isColor: true,
      description: 'Foreground color',
    },
    {
      name: 'blending',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.blending,
      description:
        'How much the image is printed into the paper (0 = exact image, 1 = image multiplied with the paper ink), needs image',
    },
    {
      name: 'distortion',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.distortion,
      description: 'Amount of image distortion following the paper surface (needs image)',
    },
    {
      name: 'background',
      type: 'boolean',
      defaultValue: defaultParams.background,
      description: 'Shows or hides the paper texture outside the image frame',
    },
    {
      name: 'roughness',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.roughness,
      description: 'Pixel noise, related to canvas (not scalable)',
    },
    {
      name: 'roughnessSize',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.roughnessSize,
      description: 'Scale of the roughness noise (needs roughness > 0)',
    },
    {
      name: 'fiber',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.fiber,
      description: 'Curly-shaped noise',
    },
    {
      name: 'fiberSize',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.fiberSize,
      description: 'Curly-shaped noise scale (needs fiber > 0)',
    },
    {
      name: 'folds',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.folds,
      description: 'Depth of the radial folds',
    },
    {
      name: 'foldCount',
      type: 'number',
      min: 1,
      max: 20,
      step: 1,
      defaultValue: defaultParams.foldCount,
      description: 'Number of radial folds (20 max), needs folds > 0',
    },
    {
      name: 'creases',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.creases,
      description: 'Depth of the creases, an independent layer over the radial folds',
    },
    {
      name: 'creaseSize',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.creaseSize,
      description: 'Size of the creases (needs creases > 0)',
    },
    {
      name: 'creaseCross',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.creaseCross,
      description: 'Depth of a single horizontal crease running across the others (needs creases > 0)',
    },
    {
      name: 'creaseOffset',
      type: 'number',
      min: -0.5,
      max: 0.5,
      defaultValue: defaultParams.creaseOffset,
      description: 'Shifts the creases across the surface (needs creases > 0)',
    },
    {
      name: 'fade',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.fade,
      description: 'Big-scale noise mask applied to the pattern',
    },
    {
      name: 'drops',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.drops,
      description: 'The visibility of speckle pattern',
    },
    {
      name: 'seed',
      type: 'number',
      min: 0,
      max: 1000,
      defaultValue: defaultParams.seed,
      description: 'Seed applied to folds, drops and fade',
    },
    ...staticImageCommonParams,
  ],
};
