import { pulsingBorderPresets } from '@paper-design/shaders-react';
import type { ShaderDef } from './shader-def-types';

const defaultParams = pulsingBorderPresets[0].params;

export const pulsingBorderDef: ShaderDef = {
  name: 'Pulsing Border',
  description: 'Luminous trails of color merging into a glowing gradient frame.',
  params: [
    {
      name: 'colors',
      type: 'string[]',
      defaultValue: [],
      isColor: true,
      description: 'Up to 5 colors',
    },
    {
      name: 'colorBack',
      type: 'string',
      defaultValue: defaultParams.colorBack,
      isColor: true,
      description: 'Background color',
    },
    {
      name: 'roundness',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.roundness,
      description: 'The border radius',
    },
    {
      name: 'thickness',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.thickness,
      description: 'The border base width',
    },
    {
      name: 'softness',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.softness,
      description: 'Border edge sharpness (0 = hard edge, 1 = smooth gradient)',
    },
    {
      name: 'intensity',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.intensity,
      description: 'Thickness of individual color spots',
    },
    {
      name: 'bloom',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.bloom,
      description: 'The power of glow (0 = normal color blending, 1 = fully additive blending)',
    },
    {
      name: 'spots',
      type: 'number',
      min: 1,
      max: 20,
      step: 1,
      defaultValue: defaultParams.spots,
      description: 'Number of spots added for each color',
    },
    {
      name: 'spotSize',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.spotSize,
      description: 'Angular size of spots',
    },
    {
      name: 'pulse',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.pulse,
      description: 'Optional pulsing animation',
    },
    {
      name: 'smoke',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.smoke,
      description: 'Optional noisy shape extending the border width',
    },
    {
      name: 'smokeSize',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.smokeSize,
      description: 'The size of the smoke effect',
    },
    {
      name: 'offsetX',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.offsetX,
      description: 'Horizontal offset of the graphics center',
    },
    {
      name: 'offsetY',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.offsetY,
      description: 'Vertical offset of the graphics center',
    },
    {
      name: 'scale',
      type: 'number',
      min: 0.01,
      max: 1,
      defaultValue: defaultParams.scale,
      description: 'Overall zoom level of the graphics',
    },
    {
      name: 'rotation',
      type: 'number',
      min: 0,
      max: 360,
      defaultValue: defaultParams.rotation,
      description: 'Overall rotation angle of the graphics',
    },
    {
      name: 'speed',
      type: 'number',
      min: 0,
      max: 2,
      defaultValue: defaultParams.speed,
      description: 'Animation speed',
    },
  ],
};
