import { pulsingBorderPresets } from '@paper-design/shaders-react';
import type { ShaderDef } from './shader-def-types';

const defaultParams = pulsingBorderPresets[0].params;

export const pulsingBorderDef: ShaderDef = {
  name: 'Pulsing Border',
  description: 'Color spots traveling around rectangular stroke (border).',
  params: [
    {
      name: 'colorBack',
      type: 'string',
      defaultValue: defaultParams.colorBack,
      isColor: true,
      description: 'Background color.',
    },
    {
      name: 'colors',
      type: 'string[]',
      defaultValue: [],
      isColor: true,
      description: 'Colors used for the effect.',
    },
    {
      name: 'roundness',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.roundness,
      description: 'Border parameters.',
    },
    {
      name: 'thickness',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.thickness,
      description: 'Border parameters.',
    },
    {
      name: 'softness',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.softness,
      description: 'Border parameters.',
    },
    {
      name: 'intensity',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.intensity,
      description: 'Thickness of individual spots.',
    },
    {
      name: 'bloom',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.bloom,
      description: 'Normal / additive color blending.',
    },
    {
      name: 'spots',
      type: 'number',
      min: 1,
      max: 20,
      step: 1,
      defaultValue: defaultParams.spots,
      description: 'Number of spots rendered per color.',
    },
    {
      name: 'spotSize',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.spotSize,
      description: 'Angular size of spots.',
    },
    {
      name: 'pulse',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.pulse,
      description: 'Optional pulsing animation.',
    },
    {
      name: 'smoke',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.smoke,
      description: 'Optional noisy shapes around the border.',
    },
    {
      name: 'smokeSize',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.smokeSize,
      description: 'Optional noisy shapes around the border.',
    },
    {
      name: 'scale',
      type: 'number',
      min: 0.01,
      max: 1,
      defaultValue: defaultParams.scale,
      description: 'Overall pattern zoom.',
    },
    {
      name: 'rotation',
      type: 'number',
      min: 0,
      max: 360,
      defaultValue: defaultParams.rotation,
      description: 'Overall pattern rotation angle.',
    },
    {
      name: 'offsetX',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.offsetX,
      description: 'Position of the center.',
    },
    {
      name: 'offsetY',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.offsetY,
      description: 'Position of the center.',
    },
    {
      name: 'speed',
      type: 'number',
      min: 0,
      max: 2,
      defaultValue: defaultParams.speed,
      description: 'Animation speed.',
    },
  ],
};
