import { spiralPresets } from '@paper-design/shaders-react';
import type { ShaderDef } from './shader-def-types';

const defaultParams = spiralPresets[0].params;

export const spiralDef: ShaderDef = {
  name: 'Spiral',
  description: '2-color spiral shape.',
  params: [
    {
      name: 'colorBack',
      type: 'string',
      defaultValue: defaultParams.colorBack,
      isColor: true,
      description: 'Colors used for the effect.',
    },
    {
      name: 'colorFront',
      type: 'string',
      defaultValue: defaultParams.colorFront,
      isColor: true,
      description: 'Colors used for the effect.',
    },
    {
      name: 'density',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.density,
      description: 'Spacing falloff to simulate radial perspective (0 = no perspective).',
    },
    {
      name: 'distortion',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.distortion,
      description: 'Per-arch shift.',
    },
    {
      name: 'strokeWidth',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.strokeWidth,
      description: 'Thickness of stroke.',
    },
    {
      name: 'strokeTaper',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.strokeTaper,
      description: 'Stroke loosing width further from center (0 for full visibility).',
    },
    {
      name: 'strokeCap',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.strokeCap,
      description: 'Extra width at the center (no effect on strokeWidth = 0.5).',
    },
    {
      name: 'noise',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.noise,
      description: 'Simplex noise distortion over the shape.',
    },
    {
      name: 'noiseFrequency',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.noiseFrequency,
      description: 'Simplex noise distortion over the shape.',
    },
    {
      name: 'softness',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.softness,
      description: 'Color transition sharpness (0 = hard edge, 1 = smooth fade).',
    },
    {
      name: 'offsetX',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.offsetX,
      description: 'Position of the center.',
    },
    {
      name: 'offsetY',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.offsetY,
      description: 'Position of the center.',
    },
    {
      name: 'scale',
      type: 'number',
      min: 0.01,
      max: 4,
      defaultValue: defaultParams.scale,
      description: 'Overall pattern zoom.',
    },
    {
      name: 'rotation',
      type: 'number',
      min: 0,
      max: 360,
      defaultValue: defaultParams.rotation,
      description: 'Overall pattern rotation angle.',
    },
    {
      name: 'speed',
      type: 'number',
      min: 0,
      max: 2,
      defaultValue: defaultParams.speed,
      description: 'Animation speed.',
    },
  ],
};
