import { spiralTunnelPresets } from '@paper-design/shaders-react';
import type { ShaderDef } from './shader-def-types';
import { animatedCommonParams } from './common-param-def';

const defaultParams = spiralTunnelPresets[0].params;

export const spiralTunnelDef: ShaderDef = {
  name: 'Spiral Tunnel',
  description: 'An immersive, hyperspeed hypnotic passage constructed from interlocking multi-colored ribbons winding into an infinite depth with glowing bloom and distortion effects.',
  params: [
    {
      name: 'color1',
      type: 'string',
      defaultValue: defaultParams.color1,
      isColor: true,
      description: 'Color of the first spiral stream layer',
    },
    {
      name: 'color2',
      type: 'string',
      defaultValue: defaultParams.color2,
      isColor: true,
      description: 'Color of the second spiral stream layer',
    },
    {
      name: 'color3',
      type: 'string',
      defaultValue: defaultParams.color3,
      isColor: true,
      description: 'Color of the third spiral stream layer',
    },
    {
      name: 'color4',
      type: 'string',
      defaultValue: defaultParams.color4,
      isColor: true,
      description: 'Color of the fourth spiral stream layer',
    },
    {
      name: 'fieldOfView',
      type: 'number',
      min: 3,
      max: 600,
      defaultValue: defaultParams.fieldOfView,
      description: 'Camera lens viewing scale altering space perspective distortion',
    },
    {
      name: 'luminosity',
      type: 'number',
      min: 0,
      max: 20,
      defaultValue: defaultParams.luminosity,
      description: 'Adjusts the distance limits of light bloom stretching inside the core',
    },
    {
      name: 'openingSize',
      type: 'number',
      min: 0,
      max: 500,
      defaultValue: defaultParams.openingSize,
      description: 'The size profile radius masking the pitch black central exit void',
    },
    {
      name: 'ribbonCount',
      type: 'number',
      min: 1,
      max: 50,
      step: 1,
      defaultValue: defaultParams.ribbonCount,
      description: 'Frequency density pattern controlling total strip repetitions',
    },
    {
      name: 'ribbonWidth',
      type: 'number',
      min: 0.01,
      max: 1.2,
      defaultValue: defaultParams.ribbonWidth,
      description: 'Edge width thickness criteria boundaries mapping active color strips',
    },
    {
      name: 'spiralDensity',
      type: 'number',
      min: 0.5,
      max: 50,
      defaultValue: defaultParams.spiralDensity,
      description: 'Tightness profile of the angular coordinate rotations winding inwards',
    },
    {
      name: 'spiralCount',
      type: 'number',
      min: 1,
      max: 8,
      step: 1,
      defaultValue: defaultParams.spiralCount,
      description: 'Number of active rendering loop shader channels to execute simultaneously',
    },
    {
      name: 'lightIntensity',
      type: 'number',
      min: 0.1,
      max: 3,
      defaultValue: defaultParams.lightIntensity,
      description: 'Global master scalar multiplier factor boosting emissions glow',
    },
    {
      name: 'distortion',
      type: 'number',
      min: 0,
      max: 30,
      defaultValue: defaultParams.distortion,
      description: 'Wave displacement calculations feeding offset curves into depth loops',
    },
    {
      name: 'hue',
      type: 'number',
      min: -180,
      max: 180,
      defaultValue: defaultParams.hue,
      description: 'Angular degrees rotational translation factor matching global output spectrum',
    },
    {
      name: 'saturation',
      type: 'number',
      min: 0,
      max: 2,
      defaultValue: defaultParams.saturation,
      description: 'Color vividness intensity multiplier processing final output pixels',
    },
    ...animatedCommonParams,
  ],
};