import { staticRadialGradientPresets } from '@paper-design/shaders-react';
import type { ShaderDef } from './shader-def-types';

const defaultParams = staticRadialGradientPresets[0].params;

export const staticRadialGradientDef: ShaderDef = {
  name: 'Static Radial Gradient',
  description: 'N-colors radial gradient.',
  params: [
    {
      name: 'colorBack',
      type: 'string',
      defaultValue: defaultParams.colorBack,
      isColor: true,
      description: 'Background color.',
    },
    {
      name: 'colors',
      type: 'string[]',
      defaultValue: [],
      isColor: true,
      description: 'Colors used for the effect.',
    },
    {
      name: 'radius',
      type: 'number',
      min: 0,
      max: 3,
      defaultValue: defaultParams.radius,
      description: 'Circle radius.',
    },
    {
      name: 'focalDistance',
      type: 'number',
      min: 0,
      max: 3,
      defaultValue: defaultParams.focalDistance,
      description: 'Gradient center offset to the circle center.',
    },
    {
      name: 'focalAngle',
      type: 'number',
      min: 0,
      max: 360,
      defaultValue: defaultParams.focalAngle,
      description: 'Gradient center offset to the circle center.',
    },
    {
      name: 'falloff',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.falloff,
      description: 'Color points distribution (0 for linear gradient).',
    },
    {
      name: 'mixing',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.mixing,
      description: '0 for stepped gradient, 0.5 for smooth transitions, 1 for pronounced color points.',
    },
    {
      name: 'distortion',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.distortion,
      description: 'Radial distortion (effective with distortion > 0).',
    },
    {
      name: 'distortionShift',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.distortionShift,
      description: 'Radial distortion (effective with distortion > 0).',
    },
    {
      name: 'distortionFreq',
      type: 'number',
      min: 0,
      max: 20,
      step: 1,
      defaultValue: defaultParams.distortionFreq,
      description: 'Radial distortion (effective with distortion > 0).',
    },
    {
      name: 'grainMixer',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainMixer,
      description: 'Shape distortion.',
    },
    {
      name: 'grainOverlay',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainOverlay,
      description: 'Post-processing blending.',
    },
    {
      name: 'offsetX',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.offsetX,
      description: 'Position of the center.',
    },
    {
      name: 'offsetY',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.offsetY,
      description: 'Position of the center.',
    },
  ],
};
