import { staticMeshGradientPresets } from '@paper-design/shaders-react';
import type { ShaderDef } from './shader-def-types';

const defaultParams = staticMeshGradientPresets[0].params;

export const staticMeshGradientDef: ShaderDef = {
  name: 'Static Mesh Gradient',
  description: 'A composition of N color spots (one per color).',
  params: [
    {
      name: 'colors',
      type: 'string[]',
      defaultValue: [],
      isColor: true,
      description: 'Colors used for the effect.',
    },
    {
      name: 'positions',
      type: 'number',
      min: 0,
      max: 100,
      defaultValue: defaultParams.positions,
      description: 'Color spot positions.',
    },
    {
      name: 'waveX',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.waveX,
      description: 'Power of sine wave distortion along X and Y axes.',
    },
    {
      name: 'waveXShift',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.waveXShift,
      description: 'Each wave phase offset.',
    },
    {
      name: 'waveY',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.waveY,
      description: 'Power of sine wave distortion along X and Y axes.',
    },
    {
      name: 'waveYShift',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.waveYShift,
      description: 'Each wave phase offset.',
    },
    {
      name: 'mixing',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.mixing,
      description: '0 for stepped gradient, 0.5 for smooth transitions, 1 for pronounced color points.',
    },
    {
      name: 'grainMixer',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainMixer,
      description: 'Shape distortion.',
    },
    {
      name: 'grainOverlay',
      type: 'number',
      min: 0,
      max: 1,
      defaultValue: defaultParams.grainOverlay,
      description: 'Post-processing blending.',
    },
    {
      name: 'offsetX',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.offsetX,
      description: 'Position of the center.',
    },
    {
      name: 'offsetY',
      type: 'number',
      min: -1,
      max: 1,
      defaultValue: defaultParams.offsetY,
      description: 'Position of the center.',
    },
    {
      name: 'scale',
      type: 'number',
      min: 0.01,
      max: 4,
      defaultValue: defaultParams.scale,
      description: 'Overall pattern zoom.',
    },
    {
      name: 'rotation',
      type: 'number',
      min: 0,
      max: 360,
      defaultValue: defaultParams.rotation,
      description: 'Overall pattern rotation angle.',
    },
  ],
};
