/**
 * Highlights the shader code samples: an import, a JSX tree, and the JS handlers and CSS stylesheets it holds.
 * The samples are generated by the docs, so this covers the syntax they use rather than all of JS.
 * Tokens are colored with the --syntax-* variables set on .syntax-highlight.
 */
export function highlightCode(code: string): string {
  return new Highlighter(code).highlightJs(false);
}

type TokenType = 'keyword' | 'string' | 'text' | 'entity' | 'number' | 'property' | 'identifier' | 'sign' | 'comment';

const keywords = new Set([
  'async',
  'await',
  'const',
  'else',
  'export',
  'false',
  'for',
  'from',
  'function',
  'if',
  'import',
  'let',
  'new',
  'null',
  'of',
  'return',
  'true',
  'typeof',
  'undefined',
]);

class Highlighter {
  private readonly code: string;
  private index = 0;

  constructor(code: string) {
    this.code = code;
  }

  /** Highlights JS up to the end of the code, or up to the brace closing the current JSX expression */
  highlightJs(isInsideBraces: boolean): string {
    let html = '';
    let depth = 0;
    let previous = '';

    while (this.index < this.code.length) {
      const rest = this.code.slice(this.index);
      const char = rest[0]!;

      if (char === '}' && isInsideBraces && depth === 0) break;

      const space = rest.match(/^\s+/)?.[0];
      if (space) {
        html += this.take(space);
        continue;
      }

      // A < starts a JSX tag unless it follows a value, where it's a comparison
      if (char === '<' && /^<[\w/>]/.test(rest) && !/[\w)\]]$/.test(previous)) {
        html += this.highlightJsxElement();
        previous = '>';
        continue;
      }

      const comment = rest.match(/^\/\/[^\n]*|^\/\*[\s\S]*?\*\//)?.[0];
      const string = rest.match(/^"(?:\\.|[^"\\])*"|^'(?:\\.|[^'\\])*'|^`(?:\\.|[^`\\])*`/)?.[0];
      const number = rest.match(/^\d*\.?\d+/)?.[0];
      const word = rest.match(/^[\w$]+/)?.[0];

      if (comment) {
        html += this.take(comment, 'comment');
      } else if (string) {
        html += this.take(string, 'string');
      } else if (number) {
        html += this.take(number, 'number');
      } else if (word) {
        const isProperty = previous === '.' || (/^[{,]$/.test(previous) && /^\s*:/.test(rest.slice(word.length)));
        html += this.take(word, keywords.has(word) ? 'keyword' : isProperty ? 'property' : 'identifier');
      } else {
        if (char === '{') depth++;
        if (char === '}') depth--;
        html += this.take(char, 'sign');
      }
      previous = string ?? number ?? word ?? char;
    }

    return html;
  }

  private highlightJsxElement(): string {
    const isClosing = this.code.startsWith('</', this.index);
    let html = this.take(isClosing ? '</' : '<', 'sign');
    const tag = this.code.slice(this.index).match(/^[\w.]*/)![0];
    html += this.take(tag, 'entity');

    while (this.index < this.code.length) {
      const rest = this.code.slice(this.index);
      const space = rest.match(/^\s+/)?.[0];
      const attribute = rest.match(/^[\w-]+/)?.[0];
      const string = rest.match(/^"[^"]*"/)?.[0];

      if (space) {
        html += this.take(space);
      } else if (rest.startsWith('/>')) {
        return html + this.take('/>', 'sign');
      } else if (rest[0] === '>') {
        html += this.take('>', 'sign');
        return isClosing ? html : html + this.highlightJsxChildren(tag);
      } else if (attribute) {
        html += this.take(attribute, 'property');
      } else if (string) {
        html += this.take(string, 'string');
      } else if (rest[0] === '{') {
        html += this.take('{', 'sign') + this.highlightJs(true) + this.take('}', 'sign');
      } else {
        html += this.take(rest[0]!, 'sign');
      }
    }

    return html;
  }

  /** Highlights children up to and including the closing tag */
  private highlightJsxChildren(tag: string): string {
    let html = '';

    while (this.index < this.code.length) {
      const rest = this.code.slice(this.index);

      if (rest.startsWith('</')) {
        return html + this.highlightJsxElement();
      } else if (rest[0] === '<') {
        html += this.highlightJsxElement();
      } else if (tag === 'style' && rest.startsWith('{`')) {
        const end = this.code.indexOf('`}', this.index + 2);
        const css = this.code.slice(this.index + 2, end === -1 ? this.code.length : end);
        html += this.take('{', 'sign') + this.take('`', 'string');
        html += highlightCss(css);
        this.index += css.length;
        html += this.take('`', 'string') + this.take('}', 'sign');
      } else if (rest[0] === '{') {
        html += this.take('{', 'sign') + this.highlightJs(true) + this.take('}', 'sign');
      } else {
        const text = rest.match(/^[^<{]+/)![0];
        html += this.take(text, text.trim() ? 'text' : undefined);
      }
    }

    return html;
  }

  /** Moves past the text, returning it as a token, or as plain text when it has no type */
  private take(text: string, type?: TokenType): string {
    if (!this.code.startsWith(text, this.index)) return '';
    this.index += text.length;
    return type ? token(type, text) : escapeHtml(text);
  }
}

const declarationPattern = /^[\w-]+\s*:(?!:)[^{};]*[;}]/;
const valueTokenPattern = /\s+|"[^"]*"|'[^']*'|#[\da-f]+\b|-?\d*\.?\d+(?:%|[a-z]+)?|[\w-]+|[(),/]|./giy;

function highlightCss(css: string): string {
  let html = '';
  let depth = 0;
  let index = 0;

  while (index < css.length) {
    const char = css[index]!;
    const rest = css.slice(index);

    if (/\s/.test(char)) {
      const space = rest.match(/^\s+/)![0];
      html += escapeHtml(space);
      index += space.length;
    } else if (char === '{' || char === '}' || char === ';') {
      depth += char === '{' ? 1 : char === '}' ? -1 : 0;
      html += token('sign', char);
      index += 1;
    } else if (rest.startsWith('/*')) {
      const end = css.indexOf('*/', index + 2);
      const comment = css.slice(index, end === -1 ? css.length : end + 2);
      html += token('comment', comment);
      index += comment.length;
    } else if (depth > 0 && declarationPattern.test(rest)) {
      const [, property, colon] = rest.match(/^([\w-]+)(\s*:)/)!;
      html += token('property', property!) + token('sign', colon!);
      index += property!.length + colon!.length;
      const valueEnd = index + rest.slice(property!.length + colon!.length).search(/[;}]/);
      html += highlightCssValue(css.slice(index, valueEnd));
      index = valueEnd;
    } else {
      // A selector or an at-rule prelude, up to its block
      const end = css.indexOf('{', index);
      const prelude = css.slice(index, end === -1 ? css.length : end).trimEnd();
      const atRule = prelude.match(/^@[\w-]+/)?.[0];
      html += atRule
        ? token('keyword', atRule) + token('entity', prelude.slice(atRule.length))
        : token('entity', prelude);
      index += prelude.length;
    }
  }

  return html;
}

function highlightCssValue(value: string): string {
  let html = '';
  valueTokenPattern.lastIndex = 0;
  for (let match = valueTokenPattern.exec(value); match; match = valueTokenPattern.exec(value)) {
    const [text] = match;
    if (/^\s/.test(text)) html += escapeHtml(text);
    else if (/^["']/.test(text)) html += token('string', text);
    else if (/^(#|-?\.?\d)/.test(text)) html += token('number', text);
    else if (/^[\w-]+$/.test(text)) html += token('identifier', text);
    else html += token('sign', text);
  }
  return html;
}

function token(type: TokenType, text: string): string {
  return text ? `<span style="color:var(--syntax-${type})">${escapeHtml(text)}</span>` : '';
}

function escapeHtml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
